# Generated by Django 3.2.5 on 2021-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=160, verbose_name='Project Category')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=160, verbose_name='Project Name')),
                ('cover', models.ImageField(default='cover.png', upload_to='project/', verbose_name='Project Image')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Published Date')),
                ('category', models.ManyToManyField(to='projects.ProjectCategory')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
