# Generated by Django 3.2.5 on 2021-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clients Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='skills'),
        ),
    ]
