# Generated by Django 3.2.5 on 2021-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210723_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='solution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='brief'),
        ),
    ]
