# Generated by Django 3.2.5 on 2021-07-23 17:03

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210723_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
