# Generated by Django 3.2 on 2021-06-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=160, verbose_name='Course Name')),
                ('cover', models.ImageField(default='cover.png', upload_to='cover/', verbose_name='Cover Image')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Published Date')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=160, verbose_name='Course Name')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Courses Categories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, null=True, verbose_name='slug')),
                ('topic', models.CharField(max_length=160, verbose_name='Topic Name')),
                ('video', models.CharField(blank=True, max_length=400, verbose_name='Url for video')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='learn.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(to='learn.CourseCategory'),
        ),
    ]
