# Generated by Django 3.2 on 2021-06-16 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 10, 33, 22, 271604, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
