# Generated by Django 3.2 on 2021-06-17 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_topic_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 14, 16, 11, 471378, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
