# Generated by Django 3.2.5 on 2021-07-23 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_topic_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 13, 51, 45, 27897, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
